version: "3"

vars:
  IMAGE: cognito-local
  TAG: 5.3.0-m2m-poolid

tasks:
  docker:build:
    desc: Build the cognito-local docker image tagged {{.IMAGE}}:{{.TAG}}
    cmds:
      - docker build -t {{.IMAGE}}:{{.TAG}} .
